backend:
  replicaCount: 1
  image:
    repository: nitish2794/triply-backend
    pullPolicy: IfNotPresent
    tag: "sha-02029b46d12237dbb90fcaca09f87de2358e2b8a"
  service:
    type: ClusterIP
    port: 8000
  env:
    otelServiceName: "triply-backend"
    otelExporterOtlpEndpoint: "http://alloy.obs.svc.cluster.local:4318"
frontend:
  replicaCount: 1
  image:
    repository: nitish2794/triply-frontend
    pullPolicy: IfNotPresent
    tag: "sha-02029b46d12237dbb90fcaca09f87de2358e2b8a"
  service:
    type: ClusterIP
    port: 8080
ingress:
  enabled: true
  className: traefik
  host: wanderist.projects.nitishsrivastava.dev
  tlsSecretName: triply-triply-tls
