backend:
  replicaCount: 1
  image:
    repository: nitish2794/triply-backend
    pullPolicy: IfNotPresent
    tag: "sha-a78a3a33cf93eebcc8800ea6b8e01a655dd455c9"
  service:
    type: ClusterIP
    port: 8000
  env:
    otelServiceName: "triply-backend"
    otelExporterOtlpEndpoint: "http://alloy.obs.svc.cluster.local:4318"
frontend:
  replicaCount: 1
  image:
    repository: nitish2794/triply-frontend
    pullPolicy: IfNotPresent
    tag: "sha-a78a3a33cf93eebcc8800ea6b8e01a655dd455c9"
  service:
    type: ClusterIP
    port: 8080
ingress:
  enabled: true
  className: traefik
  host: triply.projects.nitishsrivastava.dev
  tlsSecretName: triply-triply-tls
