backend:
  replicaCount: 1
  image:
    repository: nitish2794/triply-backend
    pullPolicy: IfNotPresent
    tag: "sha-3f97fa86748e7ff88522053b1980efc6409919e8"
  service:
    type: ClusterIP
    port: 8000
  env:
    otelServiceName: "triply-backend"
    otelExporterOtlpEndpoint: "http://alloy.obs.svc.cluster.local:4318"
  auth:
    flow: "supabase"
frontend:
  replicaCount: 1
  image:
    repository: nitish2794/triply-frontend
    pullPolicy: IfNotPresent
    tag: "sha-3f97fa86748e7ff88522053b1980efc6409919e8"
  service:
    type: ClusterIP
    port: 8080
ingress:
  enabled: true
  className: traefik
  host: wanderist.projects.nitishsrivastava.dev
  tlsSecretName: triply-triply-tls
