apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  librechat.yaml: |
    version: 1.3.5
    cache: true
    endpoints:
      custom:
        - name: "OmniRoute"
          apiKey: "${OMNIROUTE_API_KEY}"
          baseURL: "https://omniroute.tools.nitishsrivastava.dev/v1"
          models:
            default:
              - "{{ .Values.app.defaultModel }}"
            fetch: true
          titleConvo: true
          titleModel: "{{ .Values.app.titleModel }}"
          modelDisplayLabel: "OmniRoute"
