{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-data
  labels:
    app: {{ .Release.Name }}-mongodb
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{- end }}
