grafana:
  enabled: true

  adminUser: admin
  adminPassword: Nitish@grafana26

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: obs-obs-basic-auth@kubernetescrd
    hosts:
      - grafana.obs.nitishsrivastava.dev
    tls:
      - secretName: grafana-obs-tls
        hosts:
          - grafana.obs.nitishsrivastava.dev

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 8GB
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: obs-obs-basic-auth@kubernetescrd
    hosts:
      - prometheus.obs.nitishsrivastava.dev
    paths:
      - /
    tls:
      - secretName: prometheus-obs-tls
        hosts:
          - prometheus.obs.nitishsrivastava.dev

alertmanager:
  enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false