alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

server:
  enabled: true

  extraArgs:
    web.enable-remote-write-receiver: ""

  retention: "7d"

  persistentVolume:
    enabled: true
    storageClass: local-path
    size: 8Gi

  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: 700m
      memory: 1Gi

  ingress:
    enabled: false