apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: beszel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: APP_URL
              value: {{ .Values.app.url | quote }}
            - name: CHECK_UPDATES
              value: {{ .Values.app.checkUpdates | quote }}
            - name: CONTAINER_DETAILS
              value: {{ .Values.app.containerDetails | quote }}
            - name: DISABLE_PASSWORD_AUTH
              value: {{ .Values.app.disablePasswordAuth | quote }}
            - name: MFA_OTP
              value: {{ .Values.app.mfaOtp | quote }}
            - name: SHARE_ALL_SYSTEMS
              value: {{ .Values.app.shareAllSystems | quote }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 3
            failureThreshold: 20
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
