apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triply.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "triply.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "triply.name" . }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "triply.name" . }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: triply-db-dsn
                  key: dsn
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.backend.env.otelServiceName }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.backend.env.otelExporterOtlpEndpoint }}
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
